title: "mono 技术私房菜"
email: "fan91163@gmail.com"
description: "Cayman is a clean, responsive theme for GitHub Pages."
show_downloads: true
google_analytics: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for y our site, e.g. http://example.com
twitter_username: "jekyllrb"
github_username:  "denlly"
theme: "jekyll-theme-cayman"