title: mono 技术私房菜
email: fan91163@gmail.com
description: mono技术私房菜，做自己的全栈技术
show_downloads: true
google_analytics:
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "blog.monocat.cn" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Denlly Fun
github_username:  denlly

# Build settings
markdown: kramdown
theme: #jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: Denlly Fun
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins: